django_admin_user/admin_user_example/urls.py
from django.conf.urls import url
from admin_user_example import views

app_name = 'admin_user'

urlpatterns = [
    url(r'^$', views.register, name="register"),
    url(r'^user_login/$', views.user_login, name="user_login")    
]

django_admin_user/django_admin_user/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from admin_user_example import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index, name="index"),
    url(r'^register/', include('admin_user_example.urls')),
    url(r'^logout/',views.user_logout, name="logout")
]

django_admin_user/admin_user_example/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInformation(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    gender = models.CharField(max_length=50)
    profile_pic = models.ImageField(upload_to="profile_image", blank=True)

django_admin_user/admin_user_example/views.py
from django.shortcuts import render
from admin_user_example.user_forms import UserForm, UserInformationForm

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
# Create your views here.


def index(request):
    return render(request, "admin_example/index.html")


def register(request):

    registered = False

    if request.method == "POST":
        userForm = UserForm(data=request.POST)
        informationForm = UserInformationForm(data=request.POST)

        if userForm.is_valid() and informationForm.is_valid() :

            user = userForm.save()
            user.set_password(user.password)
            user.save()

            profile = informationForm.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES :
                profile.profile_pic = request.FILES["profile_pic"]


            profile.save()
            registered = True

    else:
        userForm = UserForm()
        informationForm = UserInformationForm()
        
        
    return render(request, "admin_example/user_form.html",
        context={"user_form": userForm, "information_form": UserInformationForm, "registered" : registered})



def user_login(request):

    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else :
                return HttpResponse("Account is inactive!")
        else:
            print("Login detail provided are invalid !")     
            print("Username : {} and Password : {}".format(username, password))
            return HttpResponse("Login details are invalid !")

    else :
        return render(request, 'admin_example\login.html', context={})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

django_admin_user/templates/admin_example/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav my-auto">
                <li class="nav-brand active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_user:register' %}">Register</a>
                </li>

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_user:user_login' %}">Login</a>
                </li>

                {% endif %}

            </ul>
        </div>
    </nav>


    {% block body_block%}

    {% endblock %}

</body>
</html>

django_admin_user/templates/admin_example/index.html
<!DOCTYPE html>
{% extends 'admin_example/base.html' %}

{% block body_block%}
<div class="jumbotron">
    <h1>Home Screen</h1>
</div>
{% endblock %}

django_admin_user/templates/admin_example/login.html
<!DOCTYPE html>
{% extends 'admin_example/base.html'%}

{% block body_block %}

<div class="jumbotron">

    <form action="{% url 'admin_user:user_login' %}" method="post">

        {% csrf_token %}
        <label for="username" >Username :</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" value="Login" class="btn btn-primary">

    </form>

</div>

{% endblock %}

django_admin_user/templates/admin_example/user_form.html
<!DOCTYPE html>
{% extends 'admin_example/base.html'%}

{% block body_block %}

<div class="jumbotron">
    <h1>User Registration!</h1>

    {% if registered%}
    <h1>Thank You !!</h1>
    {% else %}
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {% if user_form%}
        {{ user_form.as_p }}
        {% endif %}

        {% if information_form%}
        {{ information_form.as_p }}
        {% endif %}

        <input type="submit" value="Register" class="btn btn-primary">

    </form>
    {% endif %}
</div>

{% endblock %}